
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: jeanduarte00/gitops
  newTag: 3c99fe73afafc85e35979d09ca7c6e562f1b3241
